name       : libgpg-error
version    : '1.28'
release    : 9
source     :
    - ftp://ftp.gnupg.org/gcrypt/libgpg-error/libgpg-error-1.28.tar.gz : f50a15fdb8e623db10cf6054e98e7cf17e0fba2d05f45b7a569aaa032b4d0dc4
license    : GPL-3.0
component  : system.base
devel      : yes
emul32     : yes
summary    : library with error codes for GnuPG related software
description: |
    Libgpg-error is a small library with error codes and descriptions shared by most GnuPG related software.
patterns   :
    - devel : /usr/share/aclocal
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
