name       : libgpg-error
version    : '1.27'
release    : 8
source     :
    - ftp://ftp.gnupg.org/gcrypt/libgpg-error/libgpg-error-1.27.tar.gz : 04bdc7fd12001c797cc689b007fe24909f55aa0ee1d6d6aef967d9eebf5b2461
license    :
    - GPL-3.0
devel      : yes
summary    : library with error codes for GnuPG related software
component  : system.base
description: |
    Libgpg-error is a small library with error codes and descriptions shared by most GnuPG related software.
patterns   :
    - devel : /usr/share/aclocal
emul32     : yes
setup      : |
    %configure --disable-static --prefix=/usr
build      : |
    %make
install    : |
    %make_install
