name        : libgpg-error
version     : 1.21
release     : 4
source     :
    - ftp://ftp.gnupg.org/gcrypt/libgpg-error/libgpg-error-1.21.tar.gz : af1b6e842b564ae711d71158bba97a474ba914eeba0ba288865c68b14fc6acba
license     :
    - GPL-3.0
devel       : yes
summary     : library with error codes for GnuPG related software
description : |
    Libgpg-error is a small library with error codes and descriptions shared by most GnuPG related software.
patterns   :
    - devel: /usr/share/aclocal
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
