name       : libgpg-error
version    : 1.35
release    : 17
source     :
    - ftp://ftp.gnupg.org/gcrypt/libgpg-error/libgpg-error-1.35.tar.bz2 : cbd5ee62a8a8c88d48c158fff4fc9ead4132aacd1b4a56eb791f9f997d07e067
license    : LGPL-2.1-or-later
component  : system.base
devel      : yes
emul32     : yes
summary    : library with error codes for GnuPG related software
description: |
    Libgpg-error is a small library with error codes and descriptions shared by most GnuPG related software.
patterns   :
    - devel : /usr/share/aclocal
setup      : |
    %apply_patches
    %reconfigure --disable-static
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
