name       : libgpg-error
version    : '1.33'
release    : 15
source     :
    - ftp://ftp.gnupg.org/gcrypt/libgpg-error/libgpg-error-1.33.tar.bz2 : 5d38826656e746c936e7742d9cde072b50baa3c4c49daa168a56813612bf03ff
license    : LGPL-2.1-or-later
component  : system.base
devel      : yes
emul32     : yes
summary    : library with error codes for GnuPG related software
description: |
    Libgpg-error is a small library with error codes and descriptions shared by most GnuPG related software.
patterns   :
    - devel : /usr/share/aclocal
setup      : |
    %apply_patches
    %reconfigure --disable-static
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
